apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    node.environment=development
    http-server.http.port=8081
    query.max-memory=1GB
    query.max-memory-per-node=512MB
    discovery.uri=http://trino:8081
  jvm.config: |
    -server
    -Xmx4G
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
data:
  hive.properties: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minioAdmin
    hive.s3.aws-secret-key=minio1234
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.non-managed-table-writes-enabled=true
    # hive.allow-drop-table=true
    hive.parquet.use-column-names=true
    hive.recursive-directories=true
    hive.metastore.authentication.type=NONE
    hive.metastore-timeout=180s
    hive.s3.connect-timeout=180s
    hive.s3.socket-timeout=180s
  iceberg.properties: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minioAdmin
    hive.s3.aws-secret-key=minio1234
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.metastore-timeout=180s
    hive.s3.connect-timeout=180s
    hive.s3.socket-timeout=180s
