apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  # - ReadWriteMany
  - ReadWriteOnce
  hostPath:
    path: /dags/ # Replace with the local DAGs folder path
  persistentVolumeReclaimPolicy: Retain
