# airflow-deployment-emptydir.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.9.3
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow123$@postgres:5432/airflow
        - name: AIRFLOW_CONN_S3
          value: aws://minioadmin:minioadmin@/?endpoint_url=http:%2F%2Fminio:9000
        - name: AIRFLOW_CONN_TRINO_CONNECTION
          value: trino://admin:@trino:8081/
        - name: _PIP_ADDITIONAL_REQUIREMENTS
          value: "apache-airflow-providers-trino"
        # command: [ "sh", "-c" ]
        command: [ "bash", "-c" ]
        args:
        - |
          airflow db init && \
          airflow users create \
            --username admin \
            --password airflow123 \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com && \
          airflow webserver
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
      # volumes:
      # - name: airflow-data
      #   emptyDir: {}
      # volumes:
      # - name: airflow-data
      #   hostPath:
      #     path: /dags/ # This path matches the containerPath above
      #     type: Directory
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
