apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-reader-binding
  namespace: osclimate
subjects:
- kind: ServiceAccount
  name: default
  namespace: osclimate
roleRef:
  kind: Role
  name: airflow-pod-reader
  apiGroup: rbac.authorization.k8s.io
