apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: osclimate
  name: airflow-pod-reader
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  # verbs: [ "list" ]
  verbs: [ "get", "watch", "list" ]
