apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airflow-scheduler
  template:
    metadata:
      labels:
        component: airflow-scheduler
    spec:
      containers:
      - name: scheduler
        image: apache/airflow:3.0.2-python3.9
        command: [ "airflow", "scheduler" ]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow@postgres/airflow
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://redis:6379/0
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: db+postgresql://airflow:airflow@postgres/airflow
        - name: AIRFLOW__CORE__FERNET_KEY
          value: dGhpc2lzYWZlcm5ldGtleWZvcmFpcmZsb3cxMjM=
