apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  # storageClassName: standard
  storageClassName: local
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  # - ReadWriteMany
  - ReadWriteOnce
  hostPath:
    path: /dags # Replace with the local DAGs folder path
  persistentVolumeReclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  # storageClassName: standard
  storageClassName: local
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  # - ReadWriteMany
  - ReadWriteOnce
  hostPath:
    path: /logs # Replace with the local DAGs folder path
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-redis-pv
spec:
  # storageClassName: standard
  storageClassName: local
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  # - ReadWriteMany
  - ReadWriteOnce
  hostPath:
    path: /redis # Replace with the local DAGs folder path
  persistentVolumeReclaimPolicy: Retain
