apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      # securityContext:
      #   runAsUser: 50000 # run as airflow user
      #   runAsGroup: 50000
      #   # fsGroup: 50000      # uncomment if you want group permissions on volumes
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop: [ "ALL" ]

      containers:
      - name: airflow-webserver
        image: osclimate/airflow:2.9.3
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 50000
          runAsGroup: 50000
          capabilities:
            drop: [ "ALL" ]
        args:
        - bash
        - '-c'
        - exec airflow webserver
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow123$@postgres:5432/airflow
        - name: AIRFLOW_CONN_S3
          value: aws://minioadmin:minioadmin@/?endpoint_url=http:%2F%2Fminio:9000
        - name: AIRFLOW_CONN_TRINO_CONNECTION
          value: trino://admin:@trino:8080/
        - name: _AIRFLOW_DB_MIGRATE
          value: 'true'
        - name: _AIRFLOW_WWW_USER_CREATE
          value: 'true'
        - name: _AIRFLOW_WWW_USER_PASSWORD
          value: admin
        - name: _PIP_ADDITIONAL_REQUIREMENTS
          value: apache-airflow-providers-trino
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags

      - name: scheduler
        image: osclimate/airflow:2.9.3
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 50000
          runAsGroup: 50000
        args:
        - bash
        - '-c'
        - exec airflow scheduler
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow123$@postgres:5432/airflow"
        - name: AIRFLOW_CONN_S3
          value: aws://minioAdmin:minio1234/?endpoint_url=http:%2F%2Fminio:9000
        - name: AIRFLOW_CONN_TRINO_CONNECTION
          value: trino://admin:@trino:8080/
        - name: _PIP_ADDITIONAL_REQUIREMENTS
          value: apache-airflow-providers-trino

      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
