---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
---
# apiVersion: rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - events
  verbs:
  - create
  - get
  - list
  - delete
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-service-account-cluster-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: osclimate
roleRef:
  kind: ClusterRole
  name: airflow
  apiGroup: rbac.authorization.k8s.io
