kind: Secret
apiVersion: v1
metadata:
  name: hive-metastore-secret
  namespace: osclimate
  labels:
    app: hive-metastore
stringData:
  AWS_ACCESS_KEY_ID: minioAdmin
  AWS_SECRET_ACCESS_KEY: minio1234
  POSTGRES_DB: hivemetadb
  POSTGRES_HOST: hive-metastore-db
  POSTGRES_PASSWORD: hivemeta123$
  POSTGRES_PORT: "5432"
  POSTGRES_USER: hive

# data:
#   AWS_ACCESS_KEY_ID: bWluaW9BZG1pbg==
#   AWS_SECRET_ACCESS_KEY: bWluaW9AMTIzNA==
#   POSTGRES_DB: aGl2ZW1ldGFkYg==
#   POSTGRES_HOST: aGl2ZS1tZXRhc3RvcmUtZGI=
#   POSTGRES_PASSWORD: aGl2ZW1ldGExMjMk
#   POSTGRES_PORT: OTA4Mw==
#   POSTGRES_USER: aGl2ZQ==
