apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: osclimate
spec:
  ports:
  - name: thrift
    protocol: TCP
    port: 9083
    targetPort: 9083
  selector:
    app: hive-metastore
