apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
data:
  init-db.sh: |
    #!/bin/bash
    # Your original init-db.sh content
    echo "Running init-db script..."
    #
    # Copyright 2018-2023 contributors to the Marquez project
    # SPDX-License-Identifier: Apache-2.0
    #
    # Usage: $ ./init-db.sh

    set -eu

    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" > /dev/null <<-EOSQL
      CREATE USER ${AIRFLOW_USER};
      ALTER USER ${AIRFLOW_USER} WITH PASSWORD '${AIRFLOW_PASSWORD}';
      CREATE DATABASE ${AIRFLOW_DB};
      GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB} TO ${AIRFLOW_USER};
      CREATE USER ${MARQUEZ_USER};
      ALTER USER ${MARQUEZ_USER} WITH PASSWORD '${MARQUEZ_PASSWORD}';
      CREATE DATABASE ${MARQUEZ_DB};
      GRANT ALL PRIVILEGES ON DATABASE ${MARQUEZ_DB} TO ${MARQUEZ_USER};
      CREATE USER ${EXAMPLE_USER};
      ALTER USER ${EXAMPLE_USER} WITH PASSWORD '${EXAMPLE_PASSWORD}';
      CREATE DATABASE ${EXAMPLE_DB};
      GRANT ALL PRIVILEGES ON DATABASE ${EXAMPLE_DB} TO ${EXAMPLE_USER};
    EOSQL
  config.yml: |-
    # Enables HTTP server configuration overrides (see: https://www.dropwizard.io/en/stable/manual/configuration.html#servers)
    server:
      applicationConnectors:
      - type: http
        port: ${MARQUEZ_PORT:-5000}
        # httpCompliance: RFC7230_LEGACY
      adminConnectors:
      - type: http
        port: ${MARQUEZ_ADMIN_PORT:-5001}
    db:
      driverClass: org.postgresql.Driver
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
